# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('desc', models.TextField(default='-')),
                ('phonenumber', models.CharField(default='-', max_length=80)),
                ('url', models.CharField(default='-', max_length=80)),
                ('restaurant_type', models.CharField(default='-', max_length=80)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
