# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 09:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('anniversary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 3, 9, 3, 5, 775000, tzinfo=utc)),
        ),
    ]
