# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 01:52
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('anniversary', '0002_auto_20170803_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_star',
            field=models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 4, 1, 52, 14, 452000, tzinfo=utc)),
        ),
    ]
