# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 01:53
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('anniversary', '0003_auto_20170804_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 4, 1, 53, 54, 930000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_star',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
