# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 07:18
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('anniversary', '0004_auto_20170804_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_star', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('date', models.DateTimeField(default=datetime.datetime(2017, 8, 4, 7, 18, 38, 406000, tzinfo=utc))),
            ],
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 4, 7, 18, 38, 405000, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='choice',
            name='rest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anniversary.restaurant'),
        ),
    ]
