# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 08:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('anniversary', '0005_auto_20170804_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='num_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='choice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 7, 8, 48, 18, 499000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='choice',
            name='restaurant_star',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 7, 8, 48, 18, 499000, tzinfo=utc)),
        ),
    ]
