# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 08:50
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('anniversary', '0006_auto_20170807_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='restaurant_star_cum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='choice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 7, 8, 50, 39, 818000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='choice',
            name='restaurant_star',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 7, 8, 50, 39, 818000, tzinfo=utc)),
        ),
    ]
