# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 02:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('anniversary', '0007_auto_20170807_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 8, 2, 3, 20, 560000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='choice',
            name='restaurant_star_cum',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 8, 2, 3, 20, 560000, tzinfo=utc)),
        ),
    ]
