# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 04:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('anniversary', '0008_auto_20170808_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 8, 4, 21, 17, 989000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 8, 4, 21, 17, 989000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_star',
            field=models.CharField(default='-', max_length=80),
        ),
    ]
