# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 05:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('anniversary', '0009_auto_20170808_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='num_rating',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='restaurant_star_cum',
        ),
        migrations.AddField(
            model_name='choice',
            name='comment',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='choice',
            name='ip',
            field=models.CharField(default='-', max_length=80),
        ),
        migrations.AddField(
            model_name='choice',
            name='user_name',
            field=models.CharField(default='-', max_length=80),
        ),
        migrations.AlterField(
            model_name='choice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 9, 5, 0, 33, 714000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 9, 5, 0, 33, 714000, tzinfo=utc)),
        ),
    ]
