# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 05:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('anniversary', '0010_auto_20170809_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='restaurant_star',
        ),
        migrations.AlterField(
            model_name='choice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 9, 5, 53, 3, 721000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 9, 5, 53, 3, 721000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='phonenumber',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_type',
            field=models.CharField(choices=[(b'0', '\uce58\ud0a8'), (b'1', '\ud55c\uc2dd'), (b'2', '\uc77c\uc2dd'), (b'3', '\uc591\uc2dd'), (b'4', '\uc911\uc2dd'), (b'5', '\ud6c4\uc2dd'), (b'6', '\ubca0\ud2b8\ub0a8')], default='1', max_length=80),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='url',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
