# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 06:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('anniversary', '0011_auto_20170809_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_star',
            field=models.CharField(default='-', max_length=80),
        ),
        migrations.AlterField(
            model_name='choice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 9, 6, 3, 27, 135000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 9, 6, 3, 27, 135000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='desc',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='phonenumber',
            field=models.CharField(default='-', max_length=80),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='url',
            field=models.CharField(default='-', max_length=80),
        ),
    ]
