# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-27 05:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('anniversary', '0012_auto_20170809_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 27, 5, 7, 55, 726411, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 27, 5, 7, 55, 725677, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_type',
            field=models.CharField(choices=[('\uce58\ud0a8', '\uce58\ud0a8'), ('\ud55c\uc2dd', '\ud55c\uc2dd'), ('\uc77c\uc2dd', '\uc77c\uc2dd'), ('\uc591\uc2dd', '\uc591\uc2dd'), ('\uc911\uc2dd', '\uc911\uc2dd'), ('\ud6c4\uc2dd', '\ud6c4\uc2dd'), ('\ubca0\ud2b8\ub0a8', '\ubca0\ud2b8\ub0a8')], default='\ud55c\uc2dd', max_length=80),
        ),
    ]
